// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyC6dP7Kx4_-OXPLeRvXJ4ylg8HmRmcgBik',
    appId: '1:409164652098:web:9069790f25c0fc2b2a97db',
    messagingSenderId: '409164652098',
    projectId: 'cloudfit-3c00a',
    authDomain: 'cloudfit-3c00a.firebaseapp.com',
    storageBucket: 'cloudfit-3c00a.firebasestorage.app',
    measurementId: 'G-V6M5CG9F8V',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDQVvyv4U9h7kJhKGbUnvPNDHgQR9s30r0',
    appId: '1:409164652098:android:b264fbe0b9da50e32a97db',
    messagingSenderId: '409164652098',
    projectId: 'cloudfit-3c00a',
    storageBucket: 'cloudfit-3c00a.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBhPixvi8wENQ6A3Zn0KwmTNv00wYRaP9o',
    appId: '1:409164652098:ios:9efadf21f7856e4a2a97db',
    messagingSenderId: '409164652098',
    projectId: 'cloudfit-3c00a',
    storageBucket: 'cloudfit-3c00a.firebasestorage.app',
    iosBundleId: 'com.example.flutterApplicationCloudfit',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBhPixvi8wENQ6A3Zn0KwmTNv00wYRaP9o',
    appId: '1:409164652098:ios:9efadf21f7856e4a2a97db',
    messagingSenderId: '409164652098',
    projectId: 'cloudfit-3c00a',
    storageBucket: 'cloudfit-3c00a.firebasestorage.app',
    iosBundleId: 'com.example.flutterApplicationCloudfit',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyC6dP7Kx4_-OXPLeRvXJ4ylg8HmRmcgBik',
    appId: '1:409164652098:web:2d12d869213ebda42a97db',
    messagingSenderId: '409164652098',
    projectId: 'cloudfit-3c00a',
    authDomain: 'cloudfit-3c00a.firebaseapp.com',
    storageBucket: 'cloudfit-3c00a.firebasestorage.app',
    measurementId: 'G-4MC8H77QE3',
  );
}
